config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users
  resources :movies do
  	member do
  		post :favorite
  		post :unfavorite
      put "like", to: "movies#upvote"
      put "dislike", to: "movies#downvote"
  	end
    resources :reviews
  end

  namespace :account do
  	resources :favorites
    resources :reviews
  end
	root 'movies#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/movie.rb
class Movie < ApplicationRecord
	has_many :reviews
	belongs_to :user
	has_many :movie_relationships
	has_many :members, :through => :movie_relationships, :source => :user
	validates :title, presence: true
	has_attached_file :avatar, styles: { medium: "300x450>", thumb: "200x200#" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  ratyrate_rateable "color", "shape", "taste"
  acts_as_votable
end

app/models/movie_relationship.rb
class MovieRelationship < ApplicationRecord
	belongs_to :user
	belongs_to :movie
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :user, optional: true
	belongs_to :movie
	validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :movies
  has_many :reviews
  has_many :movie_relationships
  has_many :favorited_movies, :through => :movie_relationships, :source => :movie

  def has_favorited?(movie)
  	favorited_movies.include?(movie)
  end


  def favorite!(movie)
  	favorited_movies << movie
  end

  def unfavorite!(movie)
  	favorited_movies.delete(movie)
  end

  ratyrate_rater
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

    # ...

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
      devise_parameter_sanitizer.permit(:account_update, keys: [:nickname])
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
	before_action :find_movie, only: [:edit, :update, :destroy]

	def index
		@movies = Movie.all
	end

	def show
		@movie = Movie.find(params[:id])
		@reviews = Review.where(movie_id: @movie.id).order("created_at DESC")
	end

	def new
		@movie = Movie.new
	end

	def create
		@movie = Movie.new(movie_params)
		@movie.user = current_user
		if @movie.save
			redirect_to movies_path, notice: "Created Successfully!"
		else
			render :new
		end
	end

	def edit
	end

	def update
		if @movie.update(movie_params)
			redirect_to movie_path, notice: "Updated Successfully!"
		end
	end

	def destroy
		@movie.destroy
		redirect_to root_path, warning: "Moive Deleted!"
	end

	def favorite
		@movie = Movie.find(params[:id])
		if !current_user.has_favorited?(@movie)
			current_user.favorite!(@movie)
			flash[:notice] = "Favorited Successfully! "
		else
			flash[:alert] = "Already Favorited!"
		end

		redirect_to :back
	end

	def unfavorite
		@movie = Movie.find(params[:id])
		if current_user.has_favorited?(@movie)
			current_user.unfavorite!(@movie)
			flash[:warning] = "Unfavorited Successfully!"
		end
		redirect_to :back
	end

	def upvote
    @movie = Movie.find(params[:id])
    @movie.upvote_by current_user
    redirect_to :back
	end

	def downvote
    @movie = Movie.find(params[:id])
    @movie.downvote_by current_user
    redirect_to :back
	end

	private

	def find_movie
		@movie = Movie.find(params[:id])

		if current_user != @movie.user
			flash[:alert] = "You have no permission!"
			redirect_to root_path
		end
	end

	def movie_params
		params.require(:movie).permit(:title, :description, :director, :movie_length, :avatar)
	end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :authenticate_user!, only: [:create, :new, :destroy]


	def new
		@movie = Movie.find(params[:movie_id])
		@review = Review.new
	end

	def create
		@movie = Movie.find(params[:movie_id])
		@movie.user = current_user
		@review = Review.new(review_params)
		@review.movie = @movie

		if @review.save
			redirect_to @movie
		else
			render :new
		end
	end

	def destroy
		@movie = Movie.find(params[:movie_id])
		@review = Review.find(params[:id])
		@review.destroy
		redirect_to movie_path(@movie)
	end

	private
	def review_params
		params.require(:review).permit(:comment)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		flash[:notice] = "Welcome to Chatting-Moives! CLick here to <a href='#{url_for(new_user_registration_path)}'> Sign Up</a>!".html_safe
	end
end

app/helpers/account/movies_helper.rb
module Account::MoviesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning" 
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<div class="row">
<footer class="container-fluid footer" style="margin-top: 50px;">
    <p class="text-center">Copyright ©2017 Chatting-Movies
        <br>Design by <a href="http://fanliangchun.com" target="_blank">fanliangchun<i class="fa fa-first-order fa-fw" aria-hidden="true"></i></a>
        
    </p>
</footer>
</div>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"><i class="fa fa-film fa-lg fa-fw" aria-hidden="true"></i> 热门影评网 </a>

        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <% if current_user %>
                <li class="active"><%= link_to("新增电影", new_movie_path) %></li>
              <% end %>
               <% if !current_user %>
                  <li><%= link_to(content_tag(:i, "注册", class: "fa fa-user-plus"), new_user_registration_path) %> </li>
                  <li><%= link_to(content_tag(:i, "登入", class: "fa fa-sign-in"), new_user_session_path) %></li>
                <% else %>
                  
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-user-circle fa-lg" aria-hidden="true"> Hi!, <%= current_user.nickname %></i>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li><%= link_to(content_tag(:i, "我收藏的影片", class: "fa fa-star"), account_favorites_path)  %></li>
                      <li class="divider"></li>
                      <li> <%= link_to(content_tag(:i, "登出", class: "fa fa-sign-out"), destroy_user_session_path, method: :delete) %> </li>
                    </ul>
                  </li>
                <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieReview</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="container-fluid">
      <div class="row">
  		  <%= render 'common/navbar' %>
      </div>
      <div id="wrap">
        <div id="main" class="clear-top">
    		<%= render 'common/flashes' %>
    		<%= yield %>
        </div>
      </div>
  	</div>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <%= yield :handwrite_javascript  %>
  </body>
  	<%= render 'common/footer' %>
</html>